general.import = ["./alacritty-theme/themes/catppuccin.toml"]

[env]
TERM = "xterm-256color"

# Window settings
[window]
decorations = "None" # This hides the title bar
padding.x = 10
padding.y = 5

# # Font settings
[font]
normal.family = "FiraCode Nerd Font Propo"
bold.family = "FiraCode Nerd Font Propo"
italic.family = "FiraCode Nerd Font Propo"
bold_italic.family = "FiraCode Nerd Font Propo"

size = 16.0
builtin_box_drawing = true

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"
