theme = "tokyonight_storm" # good default base16_transparent tokyonight_storm
[editor]
# scrolloff = 15
auto-format = true
continue-comments = false
true-color = true
gutters = ["diff", "diagnostics", "spacer"] # add "line-numbers" if needed
insert-final-newline = false
# rainbow-brackets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.auto-save]
focus-lost = true

[editor.lsp]
enable = true
display-messages = false
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = false
snippets = true
goto-reference-include-declaration = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.smart-tab]
enable = false

[keys.normal]
# Personal preference
# o = ["open_below", "normal_mode"]
# O = ["open_above", "normal_mode"]

"C-c" = "copy_selection_on_prev_line"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
"C-b" = []                                   # Unbinds Ctrl-b in normal mode
"C-n" = ["move_line_down"]
"C-p" = ["move_line_up"]
# m = "select_mode"
"X" = "extend_line_above"
"%" = "select_all"

[keys.insert]
"C-y" = ["completion", "normal_mode", "insert_mode"]
"C-n" = ["move_line_down"]
"C-p" = ["move_line_up"]

# [keys.normal.space]
# "t" = [
#   "yank_to_clipboard",
#   ":sh tmux paste-buffer -t right; tmux send-keys -t right Enter",
# ]

[keys.normal.space.t]
"s" = ["yank_to_clipboard", ":sh send-to-tmux"]
# "r" = [":sh steel %[buffer_name]"]
"r" = [":sh uv run %[buffer_name]"]
"t" = [":sh echo $(uv run pytest -q --tb=line --disable-warnings)"]

[keys.select.space.t]
"s" = ["yank_to_clipboard", ":sh send-to-tmux"]
# "r" = [":sh steel %[buffer_name]"]
"r" = [":sh uv run %[buffer_name]"]
"t" = [":sh echo $(uv run pytest -q --tb=line --disable-warnings)"]

[keys.normal.space.t.c]
"r" = [":config-reload"]
"o" = [":config-open"]

[keys.normal.space.w]
"w" = [":write"]

[keys.normal.space.q]
"q" = [":quit-all"]

[keys.normal.space.l]
"s" = [":lsp-stop"]
"r" = [":lsp-restart"]
"w" = [":lsp-workspace-command"]
"m" = [":set-language markdown"]


# create a new minor mode bound to `+`
[keys.normal."+"]
"f" = ":format"
"t" = ":pipe 'sqlfmt-rs -c'"
# m = ":run-shell-command echo 2"
# c = ":run-shell-command cargo build"
# t = ":run-shell-command cargo test"
# n = ":run-shell-command echo 3"
[keys.select."+"]
"f" = ":format"
"t" = ":pipe 'sqlfmt-rs -c'"
