# LSP Server Config
[language-server.tinymist]
command = "tinymist"

[language-server.sqlfluff-lsp]
command = "sqlfluff-lsp"
args = ["--stdio"]
config = { dialect = "databricks" }

[language-server.databricks-sql-lsp]
command = "databricks-sql-lsp"

[language-server.steel-ls]
command = "steel-language-server"

[language-server.buffer-language-server]
command = "buffer-language-server"

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

[language-server.scls-python]
command = "simple-completion-language-server"

[language-server.scls-python.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = false                # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)


[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.markdown-oxide]
command = "markdown-oxide"

[language-server.vale-ls]
command = "vale-ls"

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config.python.analysis]
typeCheckingMode = "off"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "off"

# if you choose `ruff` itself
[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ty.config.ty]
disableLanguageServices = false

[language-server.gpt]
command = "helix-gpt --handler=codeium"

# Language Config

[[language]]
name = "csv"
file-types = ["csv"]
scope = "source.csv"

[[grammar]]
name = "csv"
source.git = "https://github.com/weartist/rainbow-csv-tree-sitter"
source.rev = "896e6d09b23a1b0d87e45bf97ca34a249f41495c"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["scls", "basedpyright", "ty", "ruff"]
# language-servers = ["scls", "basedpyrigh","ruff", "ty"]                                       
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = 'prettierd', args = ["--parser", "yaml"] }
auto-format = true
language-servers = ["yaml-language-server", "ansible-language-server"]

[[language]]
name = "markdown"
file-types = ["md"]
language-servers = [
  "buffer-language-server",
  "harper-ls",
  # "vale-ls",
  "markdown-oxide",
]

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettierd', args = [".html"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettierd', args = [".css"] }
auto-format = true

# [[language]]
# name = "scss"
# formatter = { command = 'prettierd', args = [".scss"] }
# auto-format = true
# language-servers = ["gpt", "vale-ls"]
# file-types = ["txt", "md"]

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "nu"
auto-format = true
formatter = { command = "topiary", args = ["format", "--language", "nu"] }

[[grammar]]
name = "r"
source = { git = "https://github.com/r-lib/tree-sitter-r", rev = "main" }

[[language]]
name = "sql"
language-servers = ["databricks-sql-lsp"]
formatter = { command = "sqlfastfmt" }
auto-format = true

[[language]]
name = "scheme"
language-servers = ["steel-ls"]
formatter = { command = "raco", args = [
  "fmt",
  "--width",
  "60",
  "--indent",
  "0",
  "--max-blank-lines",
  "2",
] }
auto-format = true

[[language]]
name = "typst"
language-servers = ["tinymist"]                            # "harper-ls"
auto-format = true
formatter = { command = "typstyle", args = ["--inplace"] }
